/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/gltf/crown3/scene.gltf -r public
Author: Pieter Ferreira (https://sketchfab.com/Badboy17Aiden)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/golden-crown-5689a9525a2c425d93f7d483b93d8cfa
Title: Golden crown
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export function Crown3(props) {
  const meshRef = useRef(null);

  useFrame(() => {
    if (!meshRef.current) {
      return;
    }
    meshRef.current.rotation.y -= 0.004;
  });

  const { nodes, materials } = useGLTF('/gltf/crown3/scene.gltf')
  return (
    <group ref={meshRef} {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.None} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/gltf/crown3/scene.gltf')
