/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/gltf/crown/scene.gltf -r public
Author: VHM777 (https://sketchfab.com/gizacorp01)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/royal-crown-36edb23a404349709c9da94f136351e9
Title: Royal Crown
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Crown(props) {
  const meshRef = useRef(null);

  useFrame(() => {
    if (!meshRef.current) {
      return;
    }
    meshRef.current.rotation.y -= 0.002;
  });

  const { nodes, materials } = useGLTF("/gltf/crown/scene.gltf");
  return (
    <group ref={meshRef} {...props} dispose={null}>
      <group position={[0.07, 0, -0.03]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.02, 0, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.Material} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/gltf/crown/scene.gltf");
