/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/gltf/crown/scene.gltf -r public
Author: aetherowl (https://sketchfab.com/aetherowl)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/simple-low-poly-crown-e2462871cc894914adbdb8722838c3b0
Title: Simple Low Poly Crown
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Crown(props) {
  const { nodes, materials } = useGLTF("/gltf/crown/scene.gltf");

  const meshRef = useRef(null);

  useFrame(() => {
    if (!meshRef.current) {
      return;
    }
    meshRef.current.rotation.y -= 0.004;
  });

  return (
    <group ref={meshRef} {...props} dispose={null}>
      <mesh geometry={nodes.Crown_CrownMat_0.geometry} material={materials.CrownMat} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  );
}

useGLTF.preload("/gltf/crown/scene.gltf");
