/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/gltf/diamond-blue/scene.gltf -r public
Author: Kugatsu Tsukai 3D Models Hub (https://sketchfab.com/KugatsuT)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blue-diamond-free-giveaway-618d614891354c1f86f07845080e13e7
Title: Blue Diamond - Free Giveaway
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function DiamondBlue(props) {
  const { nodes, materials } = useGLTF("/gltf/diamond-blue/scene.gltf");
  const meshRef = useRef(null);

  useFrame(() => {
    if (!meshRef.current) {
      return;
    }
    meshRef.current.rotation.y -= 0.002;
  });

  return (
    <group ref={meshRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DiamondOutside} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  );
}

useGLTF.preload("/gltf/diamond-blue/scene.gltf");
