/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/gltf/diamond/scene.gltf -r public
Author: aysenaz (https://sketchfab.com/Aysenazkara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/diamond-8540be07fb3d441f8cca4e9fd45c9367
Title: Diamond
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Diamond(props) {
  const { nodes, materials } = useGLTF("/gltf/diamond/scene.gltf");

  const meshRef = useRef(null);

  useFrame(() => {
    if (!meshRef.current) {
      return;
    }
    meshRef.current.rotation.y -= 0.004;
  });

  return (
    <group ref={meshRef} {...props} dispose={null}>
      <mesh geometry={nodes.Diamond_Diamond_0.geometry} material={materials.Diamond} />
    </group>
  );
}

useGLTF.preload("/gltf/diamond/scene.gltf");
