/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/gltf/diamond-solid/scene.gltf -r public
Author: fakepad (https://sketchfab.com/fakepad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/diamond-49281469d4714f5f9ec03b992cd3612c
Title: Diamond
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function DiamondTrans(props) {
  const { nodes, materials } = useGLTF('/gltf/diamond-solid/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.dobj_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/gltf/diamond-solid/scene.gltf')
